# Tomcat 版本
version: 8.5.35
# apr 版本
aprversion: 1.6.5
aprutilversion: 1.6.1

# Tomcat 端口号定义
shutdown_port: 8005
listen_port: 8080

# server.xml 配置文件变量
connectionTimeout: 40000
maxHttpHeaderSize: 32768
redirectPort: 8443
maxThreads: 1000
minSpareThreads: 100
maxSpareThreads: 1000
acceptorThreadCount: 2
acceptCount: 2000
minProcessors: 100
maxProcessors: 2000

# catalina.sh 配置优化
VA_OPTS: "-server -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Duser.timezone=GMT+08 -Xms6144m -Xmx6144m -XX:NewSize=3072m -XX:MaxNewSize=4096m -XX:PermSize=512m -XX:MaxPermSize=512m -XX:MaxTenuringThreshold=10 -XX:NewRatio=2 -XX:+DisableExplicitGC"
