- name: 复制安装包
  copy: src={{ version }} dest=/usr/local/src/

- name: 检查 JDK 是否已经安装
  stat: path=/usr/local/jdk
  register: jdk_result

- name: 安装JDK
  shell: cd /usr/local/src/ && tar xf {{ version }} -C /usr/local/ && ln -sv /usr/local/{{ link }} /usr/local/jdk
  when: jdk_result.stat.exists == false

- name: 复制JDK环境变量
  copy: src=jdk.sh dest=/etc/profile.d/

- name: 检查 JAVA_HOME 是否存在
  shell: cat /root/.bashrc
  register: bashrc_result

- name: 引用环境变量
  shell: source /etc/profile && echo "export JAVA_HOME=/usr/local/jdk" >> /root/.bashrc && source /root/.bashrc
  when: bashrc_result.stdout.find('JAVA_HOME') == -1